from pathlib import Path

STATIC = Path(__file__).parents[1] / "app" / "static"


def test_live_nsfw_ui_hooks_and_icons_are_wired():
    icons = (STATIC / "icons.svg").read_text(encoding="utf-8")
    for name in ("nsfw-breast", "nsfw-butt", "nsfw-vulva", "nsfw-phallus"):
        assert f'id="{name}"' in icons
    app = (STATIC / "app.js").read_text(encoding="utf-8")
    assert "pulseNsfwLayer(profileSessions, xFor)" in app
    assert "data-dynamic-left" in app  # positions set by JS, CSP forbids inline styles
    nsfw = (STATIC / "nsfw.js").read_text(encoding="utf-8")
    assert "window.pulseNsfwLayer" in nsfw and "data-nsfw-pulse" in nsfw
    assert "nsfw-tl-pin" in nsfw and "liveMarkup(info.live)" in nsfw
    assert 'style=' not in nsfw
    html = (STATIC / "index.html").read_text(encoding="utf-8")
    for field in ("setNsfwLive", "setNsfwLiveFps", "setNsfwLiveLoad"):
        assert f'id="{field}"' in html


def test_phone_timeline_scrolls_and_groups_pins():
    tuning = (STATIC / "pulse-tuning.js").read_text(encoding="utf-8")
    assert "window.pulsePixelsPerHour" in tuning and "cr-pulse-scroll" in tuning and "cr-pulse-now" in tuning
    nsfw = (STATIC / "nsfw.js").read_text(encoding="utf-8")
    assert "data-nsfw-pulse-group" in nsfw and "openPulseRun" in nsfw


def test_cronologia_nsfw_symbols_are_the_session_bar():
    """3.4.20: where moments are, the REC bar is drawn as a chain of body-part symbols
    in the colour of the recording state underneath (no separate strip or pins)."""
    nsfw = (STATIC / "nsfw.js").read_text(encoding="utf-8")
    css = (STATIC / "style.css").read_text(encoding="utf-8")
    tuning = (STATIC / "pulse-tuning.js").read_text(encoding="utf-8")
    assert "nsfw-pulse-mark" not in nsfw and "nsfw-strip" not in nsfw and "nsfw-strip" not in css
    # Colour = recording state, same precedence as the bar in app.js.
    assert "rec.processing ? 'processing' : safeUrl(rec.remote_url || '') ? 'cloud' : 'rec'" in nsfw
    assert "pulseRecordingFiles(session)" in nsfw
    for state in ("s-cloud", "s-processing"):
        assert f".nsfw-bar-run.{state}" in css
    # Symbols are CSS masks (CSP img-src allows data:), one per body part.
    for cat in ("vulva", "phallus", "anus", "breast", "butt", "other"):
        assert f'.g-{cat} {{ --glyph: url("data:image/svg+xml,' in css
    # One symbol per slice of time, showing the part seen longest there: a stretch of
    # "Tette" with a short "Cazzo" does not become all "Cazzo" when zoomed out.
    assert "const sliceCat = (run, from, to)" in nsfw and "b[1] - a[1] || partRank(b[0]) - partRank(a[0])" in nsfw
    assert "GLYPH_PX = 24" in nsfw and "GLYPH_PITCH = 20.6" in nsfw and "JOIN_PX = 6" in nsfw
    # Uniform 22px tracks, symbols over the whole bar height.
    assert ".cr-pulse-track {\n  position: relative;\n  isolation: isolate;\n  height: 22px;" in css
    # Entrances are added after rendering and resume after a re-render (negative delay).
    assert "animateNewPulseItems(pulse)" in nsfw and "run.style.animationDelay" in nsfw
    assert " enter" not in nsfw.split("window.pulseNsfwLayer")[1].split("  };\n")[0]
    # The legend key survives every legend rebuild (render and resize).
    assert "window.pulseLegendExtra" in nsfw and "window.pulseLegendExtra()" in tuning
    for name in ("nsfw-wipe", "nsfw-ping"):
        assert f"@keyframes {name}" in css
    guard = css.index("@media (prefers-reduced-motion: reduce) {\n  .nsfw-bar-run,")
    assert "animation: none !important" in css[guard:guard + 200]


def test_cronologia_glyph_masks_match_their_generator():
    """The .g-* masks in style.css are generated by scripts/nsfw-glyphs.py."""
    import runpy
    script = Path(__file__).parents[1] / "scripts" / "nsfw-glyphs.py"
    rules = runpy.run_path(str(script), run_name="glyphs")["css"]()
    assert rules in (STATIC / "style.css").read_text(encoding="utf-8")
